---
title: "Thomas_section"
output: pdf_document
date: "2024-09-19"
---

```{r Load Libraries, include=FALSE}
# Load other packages here.
if (!require("cowplot")) install.packages("cowplot"); library(cowplot)
if (!require("conflicted")) install.packages("conflicted"); library(conflicted) # For dealing with conflicts
if (!require("tidyverse")) install.packages("tidyverse"); library(tidyverse)# For everything
if (!require("viridis")) install.packages("viridis"); library(viridis)
conflict_prefer_all("dplyr", quiet = TRUE)
```


```{r}
penguins <- read.csv("palmerpenguins_extended.csv")


```

```{r INSTALLING VIRIDIS + GRAPH Example}

install.packages("viridis")
library(viridis)


ggplot(penguins) +
  aes(x = bill_length_mm, y = bill_depth_mm, color = body_mass_g) +
  geom_point() + 
  scale_color_viridis("body_mass_g", option="viridis") +
  theme_classic()

#Note that you have to use the "scale_color_viridis_d("") command if you want 
#to use viridis with discrete variables.
#Options are "magma" (or "A") "inferno" (or "B") "plasma" (or "C") 
#"viridis" (or "D") "cividis" (or "E") "rocket" (or "F") "mako" (or "G") and 
# "turbo" (or "h"). We should decide on a consistent one together. 
```


#git config pull.rebase false - can use dropdown on pull menu to pull with 
#rebase automatically
#We can make branches off the project to prevent conflicts until the end 
## Guidelines:
#pull before starting to work/edit

